### ISSUE TITLE
@somerole ping not working

### ISSUE THREAD

**Issue by aussieadam** [BarryCarlyon/twitch_discord_barrycarlyon_co_uk#11]
The @everyone and @here pings do work for me, but using @somerole where somerole is a pingable role will not ping the role and will only put the text in.

**Comment by BarryCarlyon** [comment]
Thank you for the report. I'll do some testing and see what the issue is!

**Comment by BarryCarlyon** [comment]
Ah I was saving this "feature" as "platform paid for feature" as running the service is not free.

So I was intending to PayWall role pings (outside of `everyone` and `here`).

And add a thing to let people to opt in/out of the role easily as well via a discord command/etc

**Comment by BarryCarlyon** [comment]
Revisted this since I was poking around today.

It's not "locked" behind an intended paywall it's just broken. Discord is _weird_ with them. I'm investigating!

**Comment by BarryCarlyon** [comment]
This _should_ get you going

![How to get Role ID](https://raw.githubusercontent.com/BarryCarlyon/twitch_discord_barrycarlyon_co_uk/main/public/get_roles_id.png)

And then in your go live message put 

    <@&ROLEID>

So for example

    <@&983054603371298816>

Thats the role ID for my "test role" on the test discord.

I'll work on making the UI more user friendly for this
